# SPDX-FileCopyrightText: © 2026 Toon Verstraelen <Toon.Verstraelen@UGent.be>
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
    "containers/*/config.json",
    "uv.lock"
]
precedence = "override"
SPDX-FileCopyrightText = "© 2026 Toon Verstraelen <Toon.Verstraelen@UGent.be>"
SPDX-License-Identifier = "Apache-2.0"
