# SPDX-FileCopyrightText: © 2026 Toon Verstraelen <Toon.Verstraelen@UGent.be>
# SPDX-License-Identifier: Apache-2.0

name: Build and Push Container Image

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Cache downloads
        uses: actions/cache@v5
        with:
          path: |
            cache
            !cache/**/partial
            !cache/**/auxfiles
          key: single
      - name: Check Podman version
        run: podman --version
      - name: Build image
        run: |
          cd containers/gpaw-cpu/
          ./build.sh
      - name: Test image
        run: |
          cd containers/gpaw-cpu/
          ./test.sh
      - name: Login to GitHub Container Registry
        run: podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: Push images to GitHub Container Registry
        run: |
          source containers/gpaw-cpu/image_tag.sh
          podman push ${IMAGE_TAG} ghcr.io/${{ github.repository }}/${IMAGE_TAG}
